#!/bin/bash
VERSION="0.2.1"

function usage () {
	>&2 printf "pasteit $VERSION\n\n";
	>&2 printf "Commands:\n";
	>&2 printf "	-h, --help	show this usage\n";
	>&2 printf "	-e, --edit	copy url with edit mode on\n";
}

url="https://ghostbin.com/paste/new"
edit=""

while [ "$1" != "" ]; do
	case $1 in
		-h | --help )	usage
				exit
				;;
		-e | --edit )	edit="/edit"
				;;
		* )		usage
				exit 1
	esac
	shift
done

data="$HOME/.local/share/ghostbin"
if [ ! -d data ]; then
	mkdir -p $data;
fi

cookie_f="$data/.cookies"
if [ -f $cookie_f ]; then
	cookies="-b $cookie_f";
else
	cookies="-c $cookie_f";
fi

curl $cookies --data "expire=10m&lang=text" --data-urlencode "text@-" -i $url\
	| grep -Po '/paste/[A-Za-z0-9]+'\
	| sed "s|\(.\+\)|http://ghostbin.com\1$edit|"\
	| xsel;
